# Generated by Django 4.1.1 on 2022-10-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Material_Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=1000)),
                ('compromise_amount', models.IntegerField(default=0)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.provider')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='provider_id',
            field=models.ManyToManyField(to='materiales.provider'),
        ),
    ]
