# Generated by Django 4.1.1 on 2022-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_remove_material_provider_id_material_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='material',
            name='provider_id',
            field=models.ManyToManyField(to='materiales.provider'),
        ),
    ]
