# Generated by Django 4.1.1 on 2022-10-17 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_material_provider_id_material_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_arrived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('provider_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.provider')),
            ],
        ),
    ]
