# Generated by Django 4.1.1 on 2022-10-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_material_arrived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_arrived',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
