# Generated by Django 4.1.1 on 2022-10-17 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_alter_material_arrived_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve_Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('enterprise', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('factory_place_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.factory_place')),
                ('material_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
        ),
    ]
